Clarified steps to setup the discord bot
LAION-AI/Open-Assistant pull request #1140
Opened 2023-02-05 01:15 UTC by FastestMolasses

Updated the steps to properly setup the discord bot from scratch.

2023-03-12 22:49 UTC, bitplane commented on discord-bot/README.md
> +python -m venv venv
This should be `.venv` like in the backend devcontainer

2023-03-12 22:51 UTC, bitplane commented on discord-bot/README.md
> +python -m venv venv
Actually won't this create it in the wrong directory?

2023-03-12 22:58 UTC, bitplane requested changes

2023-03-12 22:58 UTC, bitplane commented on discord-bot/.gitignore
>  .venv
Not needed.

2023-03-12 22:58 UTC, bitplane commented on discord-bot/README.md
> +python -m venv venv
Should be .venv

2023-03-12 22:58 UTC, bitplane commented on discord-bot/README.md
> +env\Scripts\activate
Inconsistent with above instructions

2023-06-07 07:50 UTC, andreaskoepf commented
Closing this since we will remove the classic python data collection bot from the project.

2023-06-07 07:50 UTC, closed without merging