Swedish translation
LAION-AI/Open-Assistant pull request #1308
Opened 2023-02-07 15:45 UTC by LarsEJonasson

2023-02-08 04:53 UTC, fozziethebeat requested changes

2023-02-08 04:53 UTC, fozziethebeat commented on website/public/locales/sv/common.json
> +
This empty line can be deleted

2023-02-11 05:41 UTC, notmd approved these changes
Thank you!

2023-02-13 07:57 UTC, fozziethebeat approved these changes

2023-02-13 07:57 UTC, merged