website: Fix hydration issues side menu, move side_menu.json to common.json
LAION-AI/Open-Assistant pull request #1327
Opened 2023-02-07 20:23 UTC by rjmacarthy

Fixes #1326 

This PR moves all json in `side_menu.json` to `common.json`.  We have an issue with the side menu layout as it's a high level component and this causes hydration issues with SSR when global namespaces are not passed by default.

Any questions please reach out.

2023-02-08 05:00 UTC, fozziethebeat requested changes
Looks good, just requires merging recent changes.

2023-02-08 08:38 UTC, rjmacarthy commented
Conflicts resolved, it would be good to merge this before any more translation PRs are merged @fozziethebeat.

2023-02-08 17:24 UTC, AbdBarho approved these changes

2023-02-08 18:34 UTC, aayojezuzchrezt commented
Done [ru]

2023-02-09 02:44 UTC, fozziethebeat approved these changes

2023-02-09 02:45 UTC, merged