Correct and add Vietnamese translation
LAION-AI/Open-Assistant pull request #1336
Opened 2023-02-08 00:47 UTC by CactiStaccingCrane

Title is self-explainatory

2023-02-08 04:58 UTC, notmd requested changes

2023-02-08 04:58 UTC, notmd commented on website/public/locales/vi/common.json
> +  "copied": "Đã chép",
```suggestion
  "copied": "Đã sao chép",
```

2023-02-08 04:58 UTC, notmd commented on website/public/locales/vi/common.json
> +  "success": "Đã thành công",
```suggestion
  "success": "Thành công",
```

2023-02-08 05:02 UTC, fozziethebeat requested changes
Will approve after @notmd's suggestions are applied

2023-02-09 02:45 UTC, fozziethebeat commented
FYI: we had some refactoring and a conflict will also need to be addressed.

2023-02-09 10:21 UTC, CactiStaccingCrane commented
Will make another pull request, there's a conflict and I don't know how to respond to that

2023-02-09 10:21 UTC, closed without merging