added persian language
LAION-AI/Open-Assistant pull request #1359
Opened 2023-02-08 13:56 UTC by Torabi-srh

2023-02-08 17:29 UTC, AbdBarho commented
Blocked by #1327

2023-02-09 02:48 UTC, fozziethebeat requested changes

2023-02-09 02:48 UTC, fozziethebeat commented on website/public/locales/fa/side_menu.json
> +  "dashboard": "داشبورد",
We had some refactoring in another PR. Sorry for another ask but can you move all these entries in to common.json?

2023-02-09 02:48 UTC, fozziethebeat commented on website/next-i18next.config.js
> +      "fa",
I see we're not totally ordering these alphabetically.  Could you put this as alphabetically as you can?

2023-02-09 13:08 UTC, closed without merging