Full Russian Translation [Updated]
LAION-AI/Open-Assistant pull request #1361
Opened 2023-02-08 14:24 UTC by aayojezuzchrezt

Updated locales (synced and translated them after last update). (Not sure if I get "Good rankings", so left original next to translated, might fix it later)

2023-02-08 14:40 UTC, Klotske commented on website/public/locales/ru/side_menu.json
> +  "trollboard": "Дрска позора"
Small typo :)
Should be "Доска"

2023-02-08 17:30 UTC, AbdBarho commented
Blocked by #1327

2023-02-08 18:17 UTC, Klotske approved these changes
LGTM

2023-02-08 18:34 UTC, aayojezuzchrezt commented
Done, I guess

2023-02-09 02:49 UTC, fozziethebeat requested changes
Will approve after the new merge conflicts are resolved

2023-02-09 21:18 UTC, AbdBarho approved these changes

2023-02-10 04:04 UTC, fozziethebeat approved these changes

2023-02-10 04:10 UTC, merged