feat: romanian
LAION-AI/Open-Assistant pull request #1414
Opened 2023-02-10 06:32 UTC by MrlolDev

Added full romanian translation, I am not native speaker so it can has some errors of expressions but the same happens with other languages.

2023-02-10 07:29 UTC, MrlolDev commented
Any help with the error pls?

2023-02-10 08:16 UTC, AbdBarho commented
@MrlolDev rebase your code on top of main, the error should be fixed.

2023-02-11 03:10 UTC, fozziethebeat requested changes
If possible, could up merge in the recent changes from main? That should fix the end2end test failure.

2023-02-11 03:10 UTC, fozziethebeat commented on website/public/locales/ro/side_menu.json
> +  "dashboard": "Panou de control",
I believe this file was removed.  Can you move these entries into `common.json`?

2023-02-11 15:28 UTC, AbdBarho approved these changes
Thanks

2023-02-13 07:59 UTC, fozziethebeat approved these changes

2023-02-13 07:59 UTC, merged