Update common.json
LAION-AI/Open-Assistant pull request #1448
Opened 2023-02-10 21:30 UTC by agsoto

It's much more common "tablero" than "Tablón"

2023-02-11 03:20 UTC, fozziethebeat approved these changes

2023-02-11 03:21 UTC, fozziethebeat commented
Can you address the merge conflcits?

2023-02-13 08:00 UTC, fozziethebeat requested changes
Before we merge, can you handle the merge conflicts?

2023-02-19 09:15 UTC, AbdBarho approved these changes

2023-02-20 20:56 UTC, merged