Update ca locale
LAION-AI/Open-Assistant pull request #1450
Opened 2023-02-10 22:26 UTC by rbnval

Fix Catalan locale

2023-02-11 03:24 UTC, fozziethebeat requested changes
Overall this is good, can you address the merge conflicts?

2023-02-11 15:27 UTC, AbdBarho approved these changes

2023-02-12 08:59 UTC, notmd approved these changes
Thanks

2023-02-14 08:46 UTC, fozziethebeat approved these changes

2023-02-14 08:46 UTC, merged