add nvmrc file, default node version 16.17.0
LAION-AI/Open-Assistant pull request #1525
Opened 2023-02-12 19:01 UTC by alejandroaguilarhiguera

You can do `nvm use`

2023-02-13 08:09 UTC, fozziethebeat requested changes
Looks good! will approve after pre-commit passes.

2023-02-13 15:09 UTC, notmd approved these changes

2023-02-13 15:10 UTC, notmd commented
Hmm some how I can't merge this

2023-02-14 08:48 UTC, fozziethebeat approved these changes

2023-02-14 08:48 UTC, merged

2023-02-14 08:48 UTC, fozziethebeat commented
Seems that my request change review blocks others from merging.  I'll have to think more carefully on when to review with that setting