Add Zhihu data (#1459)
LAION-AI/Open-Assistant pull request #1863
Opened 2023-02-25 07:53 UTC by wangrui6

Adds Zhihu selected KOL data

Issue: #1459

2023-02-27 00:17 UTC, wangrui6 commented
Data scraping is still in progress and I plan to regularly update the Huggingface Dataset card here: https://huggingface.co/datasets/wangrui6/Zhihu-KOL

2023-03-01 15:18 UTC, olliestanley commented
Is there a reason to include both the notebook and the main script? It seems to be the same code in two formats. I would suggest excluding the notebook from the repo for cleanliness

2023-03-02 07:55 UTC, wangrui6 commented
any update on this PR?

2023-03-02 08:03 UTC, wangrui6 commented
> Is there a reason to include both the notebook and the main script? It seems to be the same code in two formats. I would suggest excluding the notebook from the repo for cleanliness

deduped notebook and merged with mainline.

2023-03-04 21:01 UTC, Vechtomov commented
Looks like something is wrong with your main merge. Can you recreate the pull request?

2023-03-04 22:00 UTC, wangrui6 commented
> Looks like something is wrong with your main merge. Can you recreate the pull request?

Rebased and squashed all the commits. Conflicts are also resolved.

2023-03-05 02:36 UTC, wangrui6 commented
@olliestanley @Vechtomov Can you review and leave any more comments if any?

2023-03-05 11:48 UTC, bitplane commented on data/datasets/zhihu-kol/main.py
> +    while 1:
ought to be `while True`

2023-03-05 11:53 UTC, bitplane commented
I haven't run it myself yet, but the code looks very nice. Well structured, isolated and documented, very readable. Nice work 🙂👍

2023-03-05 16:03 UTC, Vechtomov requested changes
Can you reupload the dataset? Looks like now `load_dataset("wangrui6/Zhihu-KOL")` loads only first datafile.
![image](https://user-images.githubusercontent.com/28014244/222971422-6c1eb140-5e6a-4565-a99f-1832cb9c6686.png)

2023-03-06 02:47 UTC, wangrui6 commented on data/datasets/zhihu-kol/main.py
> +    while 1:
will change it in the next PR.

2023-03-06 02:50 UTC, wangrui6 commented
> Can you reupload the dataset? Looks like now `load_dataset("wangrui6/Zhihu-KOL")` loads only first datafile. ![image](https://user-images.githubusercontent.com/28014244/222971422-6c1eb140-5e6a-4565-a99f-1832cb9c6686.png)

Fixed and merged into one file.

Question: In future, do we allow to load multiple parquet files? That will help people to manage the data version and not necessarily need to join data multiple times when there is new data obtained from crawlers. What do you think? 

Suggestion: allow `load_dataset("wangrui6/Zhihu-KOL")` to load multiple files in the data training pipeline.

2023-03-07 23:56 UTC, Vechtomov approved these changes

2023-03-08 00:04 UTC, Vechtomov commented
> > Can you reupload the dataset? Looks like now `load_dataset("wangrui6/Zhihu-KOL")` loads only first datafile. ![image](https://user-images.githubusercontent.com/28014244/222971422-6c1eb140-5e6a-4565-a99f-1832cb9c6686.png)
> 
> Fixed and merged into one file.
> 
> Question: In future, do we allow to load multiple parquet files? That will help people to manage the data version and not necessarily need to join data multiple times when there is new data obtained from crawlers. What do you think?
> 
> Suggestion: allow `load_dataset("wangrui6/Zhihu-KOL")` to load multiple files in the data training pipeline.

`load_dataset` load all files by default. It seems that format of your first file broke this feature. Check this: https://huggingface.co/docs/datasets/repository_structure

2023-03-10 22:42 UTC, bitplane approved these changes
Looks good to me

2023-03-10 22:42 UTC, merged

2023-03-10 23:15 UTC, wangrui6 commented
Question, can we still constantly update the HuggingFace data card as we are crawling more and more data every day? Or should we create a new PR to give a different pointer in the data card list?

2023-03-13 13:29 UTC, Vechtomov commented
> Question, can we still constantly update the HuggingFace data card as we are crawling more and more data every day? Or should we create a new PR to give a different pointer in the data card list?

Yes, you can update the dataset without new PR.

2023-04-23 13:33 UTC, wangrui6 commented
Update: Over 1 million highly voted question answer pairs have been uploaded to Huggingface https://huggingface.co/datasets/wangrui6/Zhihu-KOL/tree/main/data