Add tlcv2.0_oa
LAION-AI/Open-Assistant pull request #1965
Opened 2023-03-04 19:36 UTC by wannaphong

`tlcv2.0_oa` is a dataset that made for Open Assistant Text-only format. It was build from Thai Literature Corpora (TLC).

Thai Literature Corpora (TLC) is Corpora of machine-ingestible Thai classical literature texts like gutenberg. [https://attapol.github.io/tlc.html](https://attapol.github.io/tlc.html)

Hugging Face Datasets: [pythainlp/tlcv2.0_oa](https://huggingface.co/datasets/pythainlp/tlcv2.0_oa)

2023-03-05 15:28 UTC, bitplane commented
Can you strip the outputs from the notebook please? It's a bit large! Also rebase + squash commits if possible.

2023-03-12 22:32 UTC, bitplane requested changes
Looks good, just need to remove the loading file like in the other datasets :)

2023-03-12 22:32 UTC, bitplane commented on data/datasets/tlcv2.0_oa/loading_script.py
> +from datasets import load_dataset
We don't need this file anymore, it's automatically done via `__init__.py` in the parent dir 🙂

2023-03-13 13:24 UTC, Vechtomov approved these changes

2023-03-19 20:12 UTC, bitplane commented
Rebased on `main`, fixed merge conflicts and kept contributor commits rather than squash :)

2023-03-19 20:12 UTC, bitplane approved these changes

2023-03-19 20:14 UTC, merged

2023-03-19 20:54 UTC, olliestanley commented
@bitplane I think in general we decided to squash all PRs, to keep history clean. If you use "Squash and merge" in GitHub it will list the author of the commit as the person who made the PR, and anyone else who committed will also receive credit as a co-author :)

2023-03-20 12:05 UTC, bitplane commented
Sorry, I merged this before I saw the discussion on Discord. I'll squash in future :)