fix typos
LAION-AI/Open-Assistant pull request #2264
Opened 2023-03-29 00:56 UTC by RainRat

2023-03-29 01:10 UTC, melvinebenezer requested changes

2023-03-29 01:24 UTC, RainRat commented on safety/README.md
> +same on the same scale as those in ChatGPT and other commercial systems. To
yes. added to change.

2023-03-29 07:21 UTC, andrewm4894 approved these changes
Thanks!

2023-03-29 07:22 UTC, andrewm4894 commented
Might need to try run pre-commit to try get it passing.

2023-03-30 00:55 UTC, SummerSigh approved these changes
Looks good to me!

2023-03-31 16:22 UTC, andreaskoepf commented
@RainRat the llama file has been removed, could you please resolve the conflict? thx :-)

2023-03-31 23:45 UTC, RainRat commented
Ok, deleted the llama file.

2023-04-06 07:24 UTC, andreaskoepf approved these changes
Thanks a lot!

2023-04-06 07:24 UTC, merged