Add support for user deletion
LAION-AI/Open-Assistant pull request #2486
Opened 2023-04-12 17:31 UTC by olliestanley

WIP

2023-04-13 04:53 UTC, melvinebenezer requested changes

2023-04-13 04:53 UTC, melvinebenezer commented on backend/oasst_backend/user_repository.py
> +        user.display_name = "Deleted User"
I see the intention is it to keep this info coherent for inference and backend user data.
like it is used in inference/server/oasst_inference_server/routes/admin.py as well.

Can this be defined in oasst-shared/utils.py.  ?
example
` DELETED_USER = "Deleted User"` 
Similar changes can be thought for the hardcoded prefix "deleted_"
` user.username = f"deleted_{user.id}`

2023-04-14 08:45 UTC, melvinebenezer approved these changes
thanks :)

2023-04-14 15:21 UTC, AbdBarho approved these changes

2023-04-14 15:21 UTC, merged