add poetry dataset setup
LAION-AI/Open-Assistant pull request #2730
Opened 2023-04-19 00:37 UTC by CheckMC

Dataset Description
This dataset contains around 14,000 poems from the PoetryFoundation.org site. They are converted to question:response pairs, using the tags as topics.
5% of the dataset is titling requests -- the user provides a poem and asks the assistant to title it.

Languages
English

Dataset Structure
This dataset follows the OA format, which is:

INSTRUCTION (string): The user asks for a poem (from a variety of premade prompts) with topics (tags). If the given poem has no tags, the user asks for a poem on it's own.

RESPONSE (string): The assistant replies with the poem and title (from a variety of premade prompts).

SOURCE (string): The source is PoetryFoundation.org and the poet's name.

METADATA (JSON String):
{"author": "author of the original poem",
"title": "title of the poem",
"tags": "tags from poetry foundation."}

Preparing the Dataset
The dataset can be created with prepare.py. Make sure to install the required libraries in requirements.txt!

Contributions
Created by Check
Original dataset source - https://www.kaggle.com/datasets/tgdivy/poetry-foundation-poems

You can view it on my huggingface here: https://huggingface.co/datasets/checkai/instruction-poems
(this time i ran pre-commit so it should be good :D )

2023-04-19 08:17 UTC, olliestanley reviewed
Will need to remove the output CSV from the Git repo

2023-04-19 08:20 UTC, sedthh requested changes
Added some minor comments, but otherwise this is very well done. You have added all the fixes requested previously. 

Please add the dataset to the parent `__init__.py` and it should be good to go!

2023-04-19 08:20 UTC, sedthh commented on data/datasets/poetry_instruction/prepare.py
> +df["Title"] = df["Title"].str.strip()
you can also do something like
`df["Title"].apply(lambda x: "".join(x.splitlines()).strip())`

2023-04-19 08:20 UTC, sedthh commented on data/datasets/poetry_instruction/prepare.py
> +    "Compose a poem, about $topic.",
Multiple prompts, well done!

2023-04-19 08:20 UTC, sedthh commented on data/datasets/poetry_instruction/prepare.py
> +    instruction = random.choice(writing_prompts_topic).replace("$topic", str(topics))
you can also do string.format()  with "blabla {topic}" like https://www.w3schools.com/python/ref_string_format.asp

but this is okay too

2023-04-19 08:20 UTC, sedthh commented on data/datasets/poetry_instruction/prepare.py
> +    if " nan" in instruction:
please use `pd.isna(instruction)` or something similar, the "nan" is an artifact from converting NaN (missing/None) to string

2023-04-19 08:20 UTC, sedthh commented on data/datasets/poetry_instruction/requirements.txt
> +pandas==2.0.0
Well done

2023-04-19 08:20 UTC, sedthh commented on data/datasets/poetry_instruction/prepare.py
> +prepared_data.to_parquet("output.parquet", row_group_size=100, engine="pyarrow", index=False)
This is also correct.

2023-04-19 08:35 UTC, sedthh requested changes
some more comments

2023-04-19 08:35 UTC, sedthh commented on data/datasets/poetry_instruction/prepare.py
> +CURRENT_DIR = os.path.dirname(__file__)  # Gets directory path of the current python module
mabye you can also add a KAGGLE dataset loader to unpack this (I can give you an example code for this)

2023-04-20 09:47 UTC, olliestanley approved these changes

2023-04-20 10:39 UTC, merged