Add warning when submitting unchanged ranking (#272)
LAION-AI/Open-Assistant pull request #345
Opened 2023-01-03 23:26 UTC by stephancill

Fix for #272.

When the list is unchanged and the user tries to submit, they are presented with this modal:
<img width="1214" alt="Screenshot 2023-01-04 at 01 19 43" src="https://user-images.githubusercontent.com/5469870/210457601-92a1f46f-bd7f-4881-a695-fa7d33e4967b.png">

Something that may be an issue is that once the modal is presented, if the user presses Cancel, and they click submit again, it won't be presented again. More information on L27 of website/src/components/Survey/TaskControlsOverridable.tsx. Not sure how important this is but will required additional refactoring to fix.

2023-01-04 03:34 UTC, fozziethebeat requested changes
Looks good with one small change needed.  Will approve after that and after verifying another PR didn't cause a merge conflict.

2023-01-04 03:34 UTC, fozziethebeat commented on website/src/pages/evaluate/rank_assistant_replies.tsx
> +      console.log("response", newTask);
Could we drop this?

2023-01-04 09:06 UTC, stephancill commented on website/src/pages/evaluate/rank_assistant_replies.tsx
> +      console.log("response", newTask);
Oops, my bad. Fixed.

2023-01-05 12:22 UTC, andreaskoepf commented
(I removed the backend label since the proposed change is in the website code.)

2023-01-05 23:14 UTC, fozziethebeat approved these changes

2023-01-05 23:14 UTC, merged