Changes for orcacode experiment
LAION-AI/Open-Assistant pull request #3612
Opened 2023-07-27 13:31 UTC by andreaskoepf

2023-07-28 04:13 UTC, shahules786 commented
Besides this I think there is a bug in this [line](https://github.com/LAION-AI/Open-Assistant/blob/9c4eafca993f8effcd08f59d08864552dcc6999b/model/model_training/models/patching.py#L250). Config cannot be updated. I removed it from my version. Can you check that too with this PR? @andreaskoepf

2023-07-29 08:49 UTC, shahules786 requested changes

2023-07-29 08:49 UTC, shahules786 commented on model/model_training/custom_datasets/prompt_dialogue.py
> +    def __init__(self, cache_dir, num_samples: Optional[int] = None, max_char_len: int = 8000, seed: int = 42):
Isn't it better to add `data_files` as an argument with the default value "flan-5m..."?  In this way, we can change to gpt-4 version using config if required. 
`

2023-07-29 08:49 UTC, shahules786 commented on model/model_training/models/patching.py
Can you remove the `update_config` function definition too since it's not used?

2023-07-29 09:11 UTC, shahules786 commented
Nice, thanks.

2023-07-29 09:15 UTC, shahules786 approved these changes

2023-07-29 09:16 UTC, merged

2023-08-04 01:30 UTC, s0mt0chukwu approved these changes