Add `/help` command and update bot activity
LAION-AI/Open-Assistant pull request #399
Opened 2023-01-05 07:43 UTC by AlexanderHOtt

2023-01-05 07:45 UTC, AlexanderHOtt commented
![image](https://user-images.githubusercontent.com/66271487/210727972-1e75550b-0be4-4c16-aa88-c63fcb92510f.png)

2023-01-05 08:04 UTC, AlexanderHOtt commented
I need some help writing the `/tutorial` command. I can style it and everything else, but I'm not sure how specific I should be.

2023-01-05 08:56 UTC, yk approved these changes

2023-01-05 08:57 UTC, yk commented
I guess we can just make a video tutorial and then link to that

2023-01-05 12:30 UTC, andreaskoepf requested changes
Please show help for admin-commands only to bot-owner users.

2023-01-06 04:05 UTC, AlexanderHOtt commented on discord-bot/bot/messages.py
> +{_li("**`/settings log_channel <channel>`**")}
I agree that templates are probably better. 

If someone invites the bot to their server, they should be able to set the channel that the bot sends messages in. The log channel is a *server specific* configuration, so anyone who can manage the server should be able to use it

2023-01-06 04:07 UTC, AlexanderHOtt commented on discord-bot/bot/messages.py
> +{_li("**`/settings log_channel <channel>`**")}
I can switch back to using templates in another PR, but I'll have to look up how to use them async. I think `aiofiles` might be the easiest way.

2023-01-06 18:42 UTC, andreaskoepf approved these changes

2023-01-06 18:42 UTC, merged