Fill DB with Mock Data
LAION-AI/Open-Assistant pull request #417
Opened 2023-01-05 19:14 UTC by Nil-Andreu

Script to fill the database with mock data.

2023-01-05 19:15 UTC, Nil-Andreu commented
I am wondering what I am doing wrong when making the git pull from the upstream branch, as then it shows duplicate commits from mine.

2023-01-06 19:14 UTC, andreaskoepf requested changes
Thnx for using PromptReposity & cmd line args! Insertion of Messages seems to be still missing. Disabling of skpi-api-key-check in md-file is not clear.

2023-01-06 19:14 UTC, andreaskoepf commented on backend/oasst_backend/utils/hugging_face.py
> +            payload: Dict[str, str] = {"inputs": input}
this is still strange. If you cannot resolve the strange git merge problem, could you maybe just create a new branch on current HEAD or main and add the two files filldb.py and the filldb.md ?

2023-01-06 19:14 UTC, andreaskoepf commented on docs/filldb.md
> +## Requirements
I am not sure why one would need to/want to set the skip api check to false? Could you explain or remove this section if it is not necessary? thx,

2023-01-06 19:14 UTC, andreaskoepf commented on backend/filldb.py
> +# TODO: Should put settings into False
Not sure what this means. Please clarify/remove.

2023-01-06 19:14 UTC, andreaskoepf commented on backend/filldb.py
> +    """Class object which fills the database: Api Client, Users & Messages."""
It says "... & Messages" but I couldn't find the code that actually inserts messages? Is this still open?

2023-01-06 19:15 UTC, andreaskoepf commented
Just noticed this is still in Draft stage .. sry for premature review.

2023-01-07 09:38 UTC, Nil-Andreu commented
> Just noticed this is still in Draft stage .. sry for premature review.

No worries! Thanks for the feedback!

2023-01-12 07:12 UTC, Nil-Andreu commented
> Just noticed this is still in Draft stage .. sry for premature review.

It is now on code review, but do not know why the Tests are failing.

2023-01-12 07:36 UTC, yk commented
@danielpatrickhug does this interfere with what you did in #613 ?

2023-01-12 08:06 UTC, Nil-Andreu commented
> @danielpatrickhug does this interfere with what you did in #613 ?

No, in fact it uses the realistic data and the work done for the creation of the messages.

2023-01-12 14:56 UTC, danielpatrickhug commented
@yk Hi, no, it doesn't look like it directly interferes w/ #613 it basically moves the seed_data logic into a FillDB, and the logic looks the same for message insertion except for a couple of changes to how the test users and API client is created. on startup, the seed_data function is still called in main.py and the realistic data should be inserted the same as it was in #613. 

From what I remember about the MockDB ticket, it was supposed to be for adding 500,000+ messages and 1000+ users and testing the leaderboard query time. Filldb should also be able to be used with a much larger dataset to accomplish that, however during instantiation of filldb, you should be able to pass in the path to the JSON file storing the messages, currently, it is hard coded.

2023-01-13 12:28 UTC, Nil-Andreu commented
> @yk Hi, no, it doesn't look like it directly interferes w/ #613 it basically moves the seed_data logic into a FillDB, and the logic looks the same for message insertion except for a couple of changes to how the test users and API client is created. on startup, the seed_data function is still called in main.py and the realistic data should be inserted the same as it was in #613.
> 
> From what I remember about the MockDB ticket, it was supposed to be for adding 500,000+ messages and 1000+ users and testing the leaderboard query time. Filldb should also be able to be used with a much larger dataset to accomplish that, however during instantiation of filldb, you should be able to pass in the path to the JSON file storing the messages, currently, it is hard coded.

Okay could do not hardcode the path to the dataset, so we could then pass another dataset that is bigger.
For the dataset of 500k+, should I use something similar as the dataset of `anthropic's helpful test dataset` that you used? If so, could you share which was the script you used to prepare the dataset?

2023-01-16 22:19 UTC, momegas approved these changes
Looks good overall. I'm new to this project, so someone more experienced should have a. better look

2023-01-16 22:19 UTC, momegas commented on backend/filldb.py
> +    def __init__(self, db_engine, num_api_clients: int = 10, num_users: int = 10, use_seed: bool = True, seed: int = 0):
Should the default be something like 500K messages?
Or is it taking a lot of time?

2023-01-16 22:19 UTC, momegas commented on backend/filldb.py
> +    def fill_messages(self):
Some more docs would be very helpful here.

2023-02-21 08:01 UTC, Nil-Andreu commented
Heey @andreaskoepf @yk, does the filling of the database already accomplished? So we can close this PR or I can keep working in it.

2023-04-28 21:25 UTC, closed without merging