Added admin dashboard link to UserMenu
LAION-AI/Open-Assistant pull request #628
Opened 2023-01-11 13:12 UTC by Klotske

Added link to `/admin` page to the `UserMenu` component.
Link is conditionally rendered depending on user role.

![Preview](https://user-images.githubusercontent.com/30481105/211814571-22cf6ac2-0e10-45b8-850c-a91ca7c78103.png)

2023-01-11 14:08 UTC, AbdBarho requested changes

2023-01-11 15:44 UTC, Klotske commented on website/src/components/Header/UserMenu.tsx
> +      },
Tested, was working without errors

Fixed in b568f12

2023-01-11 23:04 UTC, fozziethebeat approved these changes

2023-01-11 23:04 UTC, fozziethebeat commented
Will let @AbdBarho merge after verifying this works

2023-01-12 08:13 UTC, AbdBarho approved these changes

2023-01-12 08:13 UTC, merged