#769 mock service worker in storybook
LAION-AI/Open-Assistant pull request #865
Opened 2023-01-20 15:40 UTC by jojopirker

I used MSW to mock some API calls (#769). 
The calls for the `/api/valid_labels` endpoint gets mocked for all stories. 
Code is still kinda messy thats why it is a draft, feedback appreciated! :)

2023-01-21 01:41 UTC, fozziethebeat requested changes
Looks good! Before merging, can you cleanup any commented out code and get the pre-commit check to pass?

2023-01-21 01:41 UTC, fozziethebeat commented on website/src/components/Messages/MessageWithChildren.stories.tsx
> +// NoChildren.parameters = {
Can this be cleaned up?

2023-01-26 08:14 UTC, fozziethebeat commented
@jojopirker Are you able to follow up and finish this PR?  If not, I can copy it and do the finishing touches.

2023-01-26 09:56 UTC, jojopirker commented
@fozziethebeat will try to do it tonight!

2023-01-29 06:17 UTC, fozziethebeat commented
I had to fork this to get the pre-commit stuff working correctly.

Closing in favor of my replacement PR: https://github.com/LAION-AI/Open-Assistant/pull/967

2023-01-29 06:17 UTC, closed without merging